name: sonar-release

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: Version
        required: true
      dryRun:
        type: boolean
        description: Flag to enable the dry-run execution
        default: false
        required: false

jobs:
  release:
    permissions:
      id-token: write
      contents: write
    uses: SonarSource/gh-action_release/.github/workflows/main.yaml@0c9c1cc54cbdd24258f135601d1b77cfc87e67ae # 7.4.0
    with:
      version: ${{ inputs.version }}
      dryRun: ${{ inputs.dryRun }}
      publishToBinaries: true
      slackChannel: C02E6L5C01H # squad-devex-private
      skipJavascriptReleasabilityChecks: true
      createDraftRelease: false

  update-stable-channel:
    needs: release
    if: ${{ !inputs.dryRun }}
    runs-on: sonar-xs
    permissions:
      id-token: write # OIDC → Vault
      contents: read
    steps:
      - uses: SonarSource/ci-github-actions/update-release-channel@daf499c4a746267e630bbc3a30b620559e3933ba # master
        with:
          version: ${{ inputs.version }}
          channel: stable
