---
name: Update release channel

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version the channel should point at (e.g. 0.9.0.977).
        required: true
        type: string
      channel:
        description: Release channel to update.
        required: true
        type: choice
        options:
          - latest
          - stable
          - dogfood

jobs:
  update-channel:
    runs-on: sonar-xs
    environment: release-channel-admin
    permissions:
      id-token: write # OIDC → Vault
      contents: read
    steps:
      - uses: SonarSource/ci-github-actions/update-release-channel@daf499c4a746267e630bbc3a30b620559e3933ba # master
        with:
          version: ${{ inputs.version }}
          channel: ${{ inputs.channel }}
